# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
PATH=/usr/edb/as9.6/bin:$PATH
PGDATA=/var/data/edb/as9.6/data; export PGDATA
alias psql='psql edb'
alias ntslp='watch -n5 df -h'
